services:
  - type: web
    name: decentrachat-signaling
    runtime: node
    rootDir: server
    buildCommand: cd .. && npm install && npm run build && cd server && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
