//! Initialise `ndk_context` so the Android keyring store can run.
//!
//! ## Why this file exists
//!
//! `android-native-keyring-store` calls `ndk_context::android_context()`, which
//! **panics** with *"android context was not initialized"* if nothing has set
//! it. `Cargo.toml` claimed Tauri Mobile did that for us — taken from the
//! upstream README and never run on a device. It does not: Tauri 2.11.5 and wry
//! contain no reference to `ndk_context` at all.
//!
//! The result was not a keychain that degraded. It was the app aborting on
//! launch — the panic crosses `Java_..._Rust_ipc`, an `extern "C"` boundary it
//! cannot unwind through, so Rust calls `abort()`. Every launch, both phones,
//! before a single screen rendered.
//!
//! ## How
//!
//! `ndk_context::initialize_android_context` needs a `JavaVM` and an Android
//! `Context`. `JNI_OnLoad` gives us the first — nothing else in the tree
//! defines it, checked before adding this — and `ActivityThread
//! .currentApplication()` gives us the second from JNI alone, with no Kotlin
//! shim. That matters: `src-tauri/gen/` is regenerated by `tauri android init`,
//! so anything written there is lost by construction, exactly as the Gradle
//! signing config was.
//!
//! Initialisation is **deferred to first use** rather than done in
//! `JNI_OnLoad`. The library loads before `Application.onCreate` has
//! necessarily finished, and `currentApplication()` returns null until it has.
//! By the time the webview calls a keychain command the Application certainly
//! exists.

use std::ffi::c_void;
use std::sync::OnceLock;

/// The `JavaVM` pointer, captured when the library is loaded.
///
/// Held as `usize` because a raw pointer is not `Send`/`Sync` and this is read
/// from whichever thread the IPC call arrives on.
static JAVA_VM: OnceLock<usize> = OnceLock::new();

/// Captures the `JavaVM`. Called by the runtime when `libechoit_lib.so` loads.
///
/// # Safety
///
/// Called by the JVM with a valid `JavaVM` pointer.
#[no_mangle]
pub extern "system" fn JNI_OnLoad(vm: *mut jni::sys::JavaVM, _reserved: *mut c_void) -> jni::sys::jint {
    let _ = JAVA_VM.set(vm as usize);
    jni::sys::JNI_VERSION_1_6
}

/// Ensure `ndk_context` is initialised. Idempotent, and safe to call often.
///
/// The result is cached — including failure. A second attempt would call
/// `initialize_android_context` twice, which its own documentation forbids.
pub fn ensure_initialised() -> Result<(), String> {
    static ONCE: OnceLock<Result<(), String>> = OnceLock::new();
    ONCE.get_or_init(initialise).clone()
}

fn initialise() -> Result<(), String> {
    let vm_ptr = *JAVA_VM
        .get()
        .ok_or("JNI_OnLoad did not run, so no JavaVM was captured")?
        as *mut jni::sys::JavaVM;

    // SAFETY: the pointer came from the JVM itself, via JNI_OnLoad.
    let vm = unsafe { jni::JavaVM::from_raw(vm_ptr) }
        .map_err(|e| format!("could not wrap the JavaVM: {e}"))?;

    let mut env = vm
        .attach_current_thread_permanently()
        .map_err(|e| format!("could not attach this thread to the JVM: {e}"))?;

    // The Application context, reached without a Kotlin shim. This is a hidden
    // API in the sense that it is not in the SDK surface, but it is stable and
    // is how every JNI-only library obtains a Context.
    let activity_thread = env
        .find_class("android/app/ActivityThread")
        .map_err(|e| format!("ActivityThread not found: {e}"))?;

    let application = env
        .call_static_method(
            activity_thread,
            "currentApplication",
            "()Landroid/app/Application;",
            &[],
        )
        .map_err(|e| format!("currentApplication() failed: {e}"))?
        .l()
        .map_err(|e| format!("currentApplication() did not return an object: {e}"))?;

    if application.is_null() {
        return Err("currentApplication() returned null — called before the Application existed".into());
    }

    // A local reference dies when the frame does, and `ndk_context` keeps the
    // pointer for the life of the process. It must be global, and it must not
    // be dropped.
    let global = env
        .new_global_ref(&application)
        .map_err(|e| format!("could not pin the Application reference: {e}"))?;
    let context_ptr = global.as_raw() as *mut c_void;
    std::mem::forget(global);

    // SAFETY: both pointers are valid for the life of the process — the VM by
    // definition, the Context because its global reference is leaked above.
    // Called exactly once, which `ONCE` above guarantees.
    unsafe { ndk_context::initialize_android_context(vm_ptr as *mut c_void, context_ptr) };

    Ok(())
}
